# Generated by Django 5.2.1 on 2025-05-12 14:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('login', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Логин слишком короткий (мин. 5 символов)'), django.core.validators.RegexValidator(message='Логин может содержать только буквы, цифры и подчеркивания', regex='^[a-zA-Z0-9_]+$')])),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='', max_length=120, unique=True)),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('social_media', models.ManyToManyField(to='app.socialmedia')),
            ],
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.socialmediatype'),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('img_preview_url', models.URLField()),
                ('short_description', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_url', models.URLField()),
                ('img_background_url', models.URLField()),
                ('placed', models.TextField()),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourTimeSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('place_count', models.IntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reservationstatus')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tourtimespan')),
            ],
        ),
    ]
