# Generated by Django 5.2.1 on 2025-05-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='date_from',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
            preserve_default=False,
        ),
    ]
