# Generated by Django 5.2.1 on 2025-05-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_social_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='date_to',
            field=models.DateTimeField(editable=False),
        ),
    ]
