# Generated by Django 5.2.1 on 2025-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_slug_alter_socialmedia_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
