# Generated by Django 5.2.1 on 2025-05-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationstatus',
            name='status',
            field=models.CharField(choices=[('оплачено', 'Оплачено'), ('завершено', 'Завершено'), ('клиент не явился', 'Клиент не явился'), ('ожидание оплаты', 'Ожидание оплаты'), ('возврат средств', 'Возврат средств'), ('перенесено', 'Перенесено'), ('отменено', 'Отклонено')], max_length=50, unique=True),
        ),
    ]
