# Generated by Django 5.2.1 on 2025-05-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reservationstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationstatus',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('completed', 'Завершено'), ('no_show', 'Клиент не явился'), ('waiting', 'Ожидание оплаты'), ('paid_back', 'Возврат средств'), ('moved', 'Перенесено'), ('declined', 'Отклонено')], max_length=20, unique=True),
        ),
    ]
