# Generated by Django 5.2.1 on 2025-05-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_last_login_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourinfo',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
    ]
